FORMAT: 1A
HOST: http://www.parkbase.com.br/pis/0.1/

# Parkbase-Gestão

Essa API determina as comunicações dos módulos de gestão da Parkbase Integrated Solution.
O login é feito pelo sistema nativo do Django sem necessidade de representação na API.

## Dados do Usuário Pessoa Jurídica [/enterprise]

### Visualizar Informações da Empresa [GET]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "Nome_fantasia": "Jasmin Massagens",
            "Responsável": "Jasmine",
            "CNPJ" : "11111111111"
            "Email": "lindinha17@bol.com.br",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888",
        }

### Editar dados do usuário pessoa jurídica [POST]

+ Request (apllication/json)

        {
            "Nome_fantasia": "Jasmin Massagens",
            "Responsável": "Jasmine",
            "CNPJ" : "11111111111"
            "Email": "lindinha17@bol.com.br",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888",
        }

+ Response 200 (application/json)

        {
            "status": "1 - Sucesso!"
        }

## Dados do Usuário Pessoa Física [/user]


### Visualizar Informações do Usuário [GET]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "Nome": "Jasmin",
            "CPF" : "11111111111"
            "Email": "lindinha17@bol.com.br",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888"
        }

### Editar Informações do Usuário [POST]

+ Request (application/json)

        {
            "Nome": "Jasmin",
            "CPF": "11111111111",
            "Email": "lindinha17@bol.com.br",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888"
        }

+ Response 200 (application/json)

        {
            "status": "1 - Sucesso!"
        }

## Estacionamentos [/estacionamentos]

### Listar Estacionamentos [GET]

+ Request (application/json)

        {
        }

+ Response 200 (application/json)

        {
            "Estacionamentos": [
                {
                    "Id": "12315423",
                    "Nome": "Estacionamento 24h"
                }, {
                    "Id": "12315424",
                    "Nome": "Estacionamento 12h"
                }, {
                    "Id": "12315425",
                    "Nome": "Estacionamento 36h"
                }
            ]
        }

## Estacionamento [/estacionamento]

### Visualizar Informações do Estacionamento [GET]

+ Request (application/json)

        {
            "Id": "12315423"
        }

+ Response 200 (application/json)

        {
            "Nome": "Estacionamento 24h",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888",
            "Latitude": "34.00001",
            "Longitude": "34.0001",
            "Poligono" :[
                {
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                }
            ]
        }


### Criar/Editar Estacionamento [POST]
Se id do estacionamento for vazio, cria um novo estacionamento

+ Request (application/json)

        {
            "id" : "",
            "Nome": "Estacionamento 24h",
            "Endereço": "Rua dos doces",
            "Numero": "1",
            "Complemento": "Ao lado do orelhão",
            "Bairro": "Gardênia",
            "CEP": "99999999",
            "Cidade": "Carlota",
            "Estado": "RS",
            "Telefone": "53999998888",
            "Latitude": "34.00001",
            "Longitude": "34.0001",
            "Poligono" :[
                {
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                },{
                    "latidude": "34.0000000",
                    "longitude": "35.000000"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "status": "1 - Sucesso!"
        }

### Deleta o estacionamento [DELETE]
Marca o estacionamento como não listavel

+ Request (application/json)

        {
            "Id": "12315423"
        }

+ Response 200 (application/json)

        {
            "status": "1 - Sucesso?"
        }